apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: public
  tls:
    - hosts:
        - "{{ app_domain }}"
      secretName: spring-tls-secret
  rules:
    - host: "{{ app_domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring
                port:
                  name: spring